name       : qutebrowser
version    : 1.3.3
release    : 20
source     :
    - https://github.com/qutebrowser/qutebrowser/archive/v1.3.3.tar.gz : 129e562858ea93c29f14470c2f218fee0d7312b0c08e3251091217ceb0cdfe9b
license    : GPL-3.0
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5.
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python3-qt5
    - python-attrs
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    for icon_size in 16 24 32 48 64 96 128 256; do
        install -Dm 00644 icons/qutebrowser-${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/qutebrowser.png
    done
    install -Dm00644 misc/qutebrowser.desktop $installdir/usr/share/applications/qutebrowser.desktop
    install -Dm00644 icons/qutebrowser-512x512.png $installdir/usr/share/pixmaps/qutebrowser.png
