name       : qutebrowser
version    : 1.7.0
release    : 26
source     :
    - https://github.com/qutebrowser/qutebrowser/archive/v1.7.0.tar.gz : 71437cbe9b354ef0f31ba7a414d6662e1852783ecd35df2d7562cef6fb8d2faa
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python3)
    - asciidoc
rundeps    :
    - pygments
    - python3-qt5
    - python3-qtwebengine
    - python-attrs
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
build      : |
    %python3_setup
    a2x -f manpage doc/qutebrowser.1.asciidoc
install    : |
    %python3_install
    for icon_size in 16 24 32 48 64 96 128 256 512; do
        install -Dm00644 icons/qutebrowser-${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/qutebrowser.png
    done
    install -Dm00644 icons/qutebrowser.svg $installdir/usr/share/icons/hicolor/scalable/apps/qutebrowser.svg
    install -Dm00644 misc/org.qutebrowser.qutebrowser.appdata.xml  $installdir/usr/share/metainfo/org.qutebrowser.qutebrowser.appdata.xml
    install -Dm00644 ./misc/org.qutebrowser.qutebrowser.desktop $installdir/usr/share/applications/org.qutebrowser.qutebrowser.desktop
    install -Dm00644 doc/qutebrowser.1 $installdir/usr/share/man/man1/qutebrowser.1
