name       : qutebrowser
version    : 2.5.0
release    : 41
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v2.5.0/qutebrowser-2.5.0.tar.gz : e18442a230570f25918a2e89ad4d073ace46c4f59b5fdda2e80ab3c4764451fd
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python3)
    - asciidoc
rundeps    :
    - python3-qt5
    - python-jinja
    - python-qtwebengine
    - pyyaml
build      : |
    %make -f misc/Makefile
install    : |
    %make_install -f misc/Makefile PREFIX=/usr
