name       : qutebrowser
version    : 2.0.2
release    : 33
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v2.0.2/qutebrowser-2.0.2.tar.gz : 48a87e453b8932e259b7b3cabd8bc500606852f622d123388fb34e4ffe57b33b
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python3)
    - asciidoc
rundeps    :
    - python3-qt5
    - python-importlib-resources
    - python-jinja
    - python-qtwebengine
    - pyyaml
build      : |
    %make -f misc/Makefile
install    : |
    %make_install -f misc/Makefile PREFIX=/usr
