name       : qutebrowser
version    : 1.0.2
release    : 10
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v1.0.2/qutebrowser-1.0.2.tar.gz : f33281bd6d23bdfad7fbf8b85a01ae9cbc6bd343a957bbebcdd38f9ee8ae7624
license    : GPL-3.0
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5.
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python-3.5)
    - pygments
    - python3-qt5
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
rundeps    :
    - pygments
    - python3-qt5
    - python-attrs
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    for icon_size in 16 24 32 48 64 96 128 256; do
        install -Dm 00644 icons/qutebrowser-${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/qutebrowser.png
    done
    install -Dm00644 misc/qutebrowser.desktop $installdir/usr/share/applications/qutebrowser.desktop
    install -Dm00644 icons/qutebrowser-512x512.png $installdir/usr/share/pixmaps/qutebrowser.png
