name       : qutebrowser
version    : 0.11.1
release    : 9
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v0.11.1/qutebrowser-0.11.1.tar.gz : 361b56e10e78ff843c127eb1c27217d382401c5856c82e839af4d4d058f43f5d
license    : GPL-3.0
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5.
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python-3.5)
    - pygments
    - python3-qt5
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
rundeps    :
    - pygments
    - python3-qt5
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-opengl
    - python-markupsafe
    - python-pypeg2
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    for icon_size in 16 24 32 48 64 96 128 256; do
        install -Dm 00644 icons/qutebrowser-${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/qutebrowser.png
    done
    install -Dm00644 qutebrowser.desktop $installdir/usr/share/applications/qutebrowser.desktop
    install -Dm00644 icons/qutebrowser-512x512.png $installdir/usr/share/pixmaps/qutebrowser.png
