name       : qutebrowser
version    : 1.1.0
release    : 13
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v1.1.0/qutebrowser-1.1.0.tar.gz : 24e59f9901e635beac82563c10067f1b6bb78bd936e3954f2862873c55f902f0
license    : GPL-3.0
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5.
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - pygments
    - python3-qt5
    - python-attrs
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    for icon_size in 16 24 32 48 64 96 128 256; do
        install -Dm 00644 icons/qutebrowser-${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/qutebrowser.png
    done
    install -Dm00644 misc/qutebrowser.desktop $installdir/usr/share/applications/qutebrowser.desktop
    install -Dm00644 icons/qutebrowser-512x512.png $installdir/usr/share/pixmaps/qutebrowser.png
