name       : qutebrowser
version    : 0.10.1
release    : 6
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v0.10.1/qutebrowser-0.10.1.tar.gz : 57f4915f0f2b1509f3aa1cb9c47117fdaad35b4c895e9223c4eb0a6e8af51917
license    : GPL-3.0
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5.
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python-3.5)
    - pygments
    - python3-qt5
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
rundeps    :
    - pygments
    - python3-qt5
    - python-colorama
    - python-cssutils
    - python-jinja
    - python-markupsafe
    - python-pypeg2
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
    for icon_size in 16 24 32 48 64 96 128 256; do
        install -Dm 00644 icons/qutebrowser-${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/qutebrowser.png
    done
    install -Dm00644 qutebrowser.desktop $installdir/usr/share/applications/qutebrowser.desktop
    install -Dm00644 icons/qutebrowser-512x512.png $installdir/usr/share/pixmaps/qutebrowser.png
