name       : qutebrowser
version    : 2.4.0
release    : 40
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v2.4.0/qutebrowser-2.4.0.tar.gz : f2cd9abb14ebabf9630573b2fb8447be192877787dc4e3964e1b55f72a8592ec
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python3)
    - asciidoc
rundeps    :
    - python3-qt5
    - python-jinja
    - python-qtwebengine
    - pyyaml
build      : |
    %make -f misc/Makefile
install    : |
    %make_install -f misc/Makefile PREFIX=/usr
