name       : qutebrowser
version    : 2.2.3
release    : 34
source     :
    - https://github.com/qutebrowser/qutebrowser/releases/download/v2.2.3/qutebrowser-2.2.3.tar.gz : 0683f5ebc8f18fde27be4adc802f377cfc3f4cf46c2363db0a8a2acd6345eb62
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : A keyboard-driven, vim-like browser based on PyQt5
description: |
    A keyboard-driven, vim-like browser based on PyQt5.
builddeps  :
    - pkgconfig(python3)
    - asciidoc
rundeps    :
    - python3-qt5
    - python-importlib-resources
    - python-jinja
    - python-qtwebengine
    - pyyaml
build      : |
    %make -f misc/Makefile
install    : |
    %make_install -f misc/Makefile PREFIX=/usr
